datawave {
    org.jboss.security.auth.spi.RunAs required roleName=InternalUser
    datawave.security.login.DatawavePrincipalLoginModule required principalClass=datawave.security.authorization.DatawavePrincipal verifier=datawave.security.login.DatawaveCertVerifier ocspLevel=off allowUserProxying=false trustedHeaderLogin=false
}
